language: python
git:
  depth: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to check before build
before_script:
    - "python -m compileall -f ."
    - "pip install pycodestyle && pycodestyle ."
    - "python -m unittest discover"
# build nothing right now
script: "true"
