language: python
# command to install dependencies
install: "pip install -r requirements.txt"
# command to check for syntax errors
before_script: "python -m compileall -f ."
# command to run tests
script: "python -m unittest discover"
