language: python
# command to install dependencies
install: "pip install -r requirements.txt"
# command to check before build
before_script:
    - "cp settings_sample.py settings_default.py"
    - "python -m compileall -f ."
    - "pip install pep8 && pep8 ."
    - "python -m unittest discover"
# build nothing right now
script: "true"
